#!/bin/bash

# Snapshot engine ("time travel"). At first install Promptify records every
# user-owned file it touches into a MANIFEST with byte-exact copies (sha256),
# so uninstall can restore the machine to exactly how it was before — nothing
# lost, nothing left behind.
#
# MANIFEST format (pipe-separated, one per line):
#   P|<abs path>|<rel copy under backup/system/files>|<sha256 of original>
#   C|<abs path>|<sha256 of the content Promptify wrote>
#
#   P  = preserved: the file existed pre-install; restore the original copy.
#   C  = created: Promptify made this file; delete it only if it still matches
#        what we wrote (a user who edited it keeps it, reported in the verify).

sha256_of() {
    local f="$1"
    [[ -f "$f" ]] && sha256sum "$f" 2>/dev/null | awk '{print $1}'
}

init_manifest() {
    mkdir -p "$PFY_BACKUP_SYSTEM" "$PFY_BACKUP_FILES" "$PFY_BACKUP_ARCHIVES" \
             "$PFY_USERDATA" "$PFY_RUNTIME" 2>/dev/null
    if [[ ! -f "$PFY_MANIFEST" ]]; then
        {
            echo "# Promptify backup manifest (auto-generated by install)"
            echo "# P|<path>|<rel copy>|<original sha256>"
            echo "# C|<path>|<sha256 we wrote>"
        } > "$PFY_MANIFEST"
    fi
}

manifest_has() {
    local path="$1"
    grep -qF "|${path}|" "$PFY_MANIFEST" 2>/dev/null
}

# Record a file that existed before Promptify overwrote it. Idempotent.
snapshot_preserve() {
    local path="$1"
    [[ -n "$path" && -f "$path" ]] || return 0
    manifest_has "$path" && return 0
    local idx name
    idx=$(find "$PFY_BACKUP_FILES" -maxdepth 1 -type f 2>/dev/null | wc -l)
    name="f${idx}"
    while [[ -e "$PFY_BACKUP_FILES/$name" ]]; do
        idx=$((idx + 1)); name="f${idx}"
    done
    cp -p "$path" "$PFY_BACKUP_FILES/$name" 2>/dev/null || return 1
    local hash
    hash=$(sha256_of "$path")
    echo "P|${path}|${name}|${hash}" >> "$PFY_MANIFEST"
}

# Mark a file Promptify created (call right after writing it). Idempotent.
# When an entry already exists (re-apply/update rewrote the file), refresh the
# recorded hash so uninstall still matches the content we actually wrote.
snapshot_created() {
    local path="$1"
    [[ -n "$path" && -f "$path" ]] || return 0
    local hash
    hash=$(sha256_of "$path")
    if grep -q "^C|${path}|" "$PFY_MANIFEST" 2>/dev/null; then
        awk -v p="$path" -v h="$hash" '
            index($0, "C|" p "|") == 1 { $0 = "C|" p "|" h }
            { print }
        ' "$PFY_MANIFEST" > "$PFY_MANIFEST.tmp" 2>/dev/null
        mv "$PFY_MANIFEST.tmp" "$PFY_MANIFEST"
        return 0
    fi
    # Preserved files (P) are restored from backup, never C-marked.
    manifest_has "$path" && return 0
    echo "C|${path}|${hash}" >> "$PFY_MANIFEST"
}

# Full 1st-install capture: profiles + facts about the pre-install shell.
# Idempotent — later re-applies never re-capture.
capture_snapshot() {
    init_manifest
    [[ -f "$PFY_MANIFEST" ]] || return 1

    # Preserve the real profiles (or note they didn't exist).
    [[ -f "$HOME/.zshrc" ]] && snapshot_preserve "$HOME/.zshrc"
    [[ -f "$HOME/.bashrc" ]] && snapshot_preserve "$HOME/.bashrc"

    # Facts about the pre-install shell, stored once. Detection is broad on
    # purpose: a distro config (e.g. cachyos-config.zsh) loads oh-my-zsh and
    # p10k without ever naming them in ~/.zshrc.
    local orig="$HOME/.zshrc"
    if [[ -f "$orig" ]]; then
        if grep -q 'oh-my-zsh\|ohmyzsh\|cachyos-zsh-config' "$orig" 2>/dev/null; then
            record_install_fact ORIG_OMZ 1
        else
            record_install_fact ORIG_OMZ 0
        fi
        if grep -qi 'powerlevel9k\|powerlevel10k\|p10k\|cachyos-zsh-config' "$orig" 2>/dev/null \
           || [[ -f "$HOME/.p10k.zsh" ]]; then
            record_install_fact ORIG_P10K 1
        else
            record_install_fact ORIG_P10K 0
        fi
    else
        record_install_fact ORIG_OMZ 0
        record_install_fact ORIG_P10K 0
    fi

    record_install_fact LAYOUT 2
}

# ---------------------------------------------------------------------------
# Restore
# ---------------------------------------------------------------------------

# Restore a non-profile preserved file. Returns 0=restored/already-original.
plain_restore() {
    local path="$1" backup="$2"
    [[ -f "$backup" ]] || return 1
    if [[ -f "$path" ]]; then
        cmp -s "$path" "$backup" && return 0
    fi
    cp -p "$backup" "$path" 2>/dev/null
}

# Merge-restore a profile (~/.zshrc / ~/.bashrc): put the original back, then
# re-append any lines the user added while Promptify was installed. When there
# are no user additions the original is restored byte-for-byte.
restore_profile() {
    local path="$1" backup="$2"
    local managed="$PFY_PROFILE_ZSHRC"
    [[ "$path" == "$HOME/.bashrc" ]] && managed="$PFY_PROFILE_BASHRC"
    [[ -f "$backup" ]] || return 1

    # Nothing there yet → restore the original.
    if [[ ! -f "$path" ]] || cmp -s "$path" "$backup"; then
        [[ -f "$path" ]] || cp -p "$backup" "$path" 2>/dev/null
        return 0
    fi

    # Profile is (or contains) our managed line → merge user edits back on top.
    if grep -qF "$managed" "$path" 2>/dev/null; then
        local additions
        additions=$(grep -vF "$managed" "$path" \
            | grep -vF "$PFY_PROFILE_COMMENT" \
            | grep -v '^[[:space:]]*$')

        # No user edits: byte-exact restore, no extra header.
        if [[ -z "$additions" ]]; then
            cp -p "$backup" "$path" 2>/dev/null
            return 0
        fi

        local tmp
        tmp=$(mktemp)
        cp -p "$backup" "$tmp"
        echo "" >> "$tmp"
        echo "# --- Your post-Promptify additions (merged back on uninstall) ---" >> "$tmp"
        printf '%s\n' "$additions" >> "$tmp"
        cp -p "$tmp" "$path" 2>/dev/null
        rm -f "$tmp"
        return 0
    fi

    # User replaced the file entirely — never clobber it.
    return 2
}

# Revert every user-owned file recorded in the MANIFEST. Reports kept files.
restore_snapshot() {
    [[ -f "$PFY_MANIFEST" ]] || { echo "  No snapshot found."; return 1; }
    local restored=0 kept=0
    local kind path rel ours
    while IFS='|' read -r kind path rel ours; do
        [[ "$kind" == "#"* || -z "$kind" ]] && continue
        case "$kind" in
            P)
                if is_profile_path "$path"; then
                    if restore_profile "$path" "$PFY_BACKUP_FILES/$rel"; then
                        restored=$((restored + 1))
                    elif [[ $? -eq 2 ]]; then
                        kept=$((kept + 1))
                        echo -e " \e[1;33m[i]\e[0m $path was replaced by you — left as-is."
                    else
                        echo -e " \e[1;31m[!]\e[0m Could not restore $path (backup missing)."
                    fi
                else
                    if plain_restore "$path" "$PFY_BACKUP_FILES/$rel"; then
                        restored=$((restored + 1))
                    else
                        echo -e " \e[1;31m[!]\e[0m Could not restore $path (backup missing)."
                    fi
                fi
                ;;
            C)
                if [[ -f "$path" ]]; then
                    if [[ "$(sha256_of "$path")" == "$ours" ]]; then
                        rm -f "$path" 2>/dev/null
                        restored=$((restored + 1))
                    else
                        kept=$((kept + 1))
                        echo -e " \e[1;33m[i]\e[0m $path edited after install — kept."
                    fi
                fi
                ;;
        esac
    done < "$PFY_MANIFEST"
    echo -e " \e[1;34m[*]\e[0m Restored $restored file(s), kept $kept."
    return 0
}

is_profile_path() {
    [[ "$1" == "$HOME/.zshrc" || "$1" == "$HOME/.bashrc" ]]
}

# ---------------------------------------------------------------------------
# Verification ("full verify" after uninstall)
# ---------------------------------------------------------------------------

verify_cleanup() {
    local pass=0 fail=0
    echo -e "\n\e[1;34m[*]\e[0m Verifying cleanup..."

    local f
    for f in "$HOME/.zshrc" "$HOME/.bashrc"; do
        if grep -qE 'promptify/runtime|# --- Promptify Config ---' "$f" 2>/dev/null; then
            echo -e " \e[1;31m[✗]\e[0m $f still contains Promptify content."
            fail=$((fail + 1))
        else
            pass=$((pass + 1))
        fi
    done

    if [[ -f "$PFY_MANIFEST" ]]; then
        local kind path rel ours
        while IFS='|' read -r kind path rel ours; do
            [[ "$kind" == "#"* || -z "$kind" ]] && continue
            case "$kind" in
                P)
                    if [[ -f "$PFY_BACKUP_FILES/$rel" && -f "$path" ]] \
                       && cmp -s "$PFY_BACKUP_FILES/$rel" "$path"; then
                        pass=$((pass + 1))
                    else
                        echo -e " \e[1;31m[✗]\e[0m $path was not restored."
                        fail=$((fail + 1))
                    fi
                    ;;
                C)
                    if [[ -f "$path" ]]; then
                        echo -e " \e[1;33m[o]\e[0m $path kept (user-modified)."
                        pass=$((pass + 1))
                    else
                        pass=$((pass + 1))
                    fi
                    ;;
            esac
        done < "$PFY_MANIFEST"
    fi

    if [[ -d "$PFY_SYS_DIR" ]]; then
        echo -e " \e[1;31m[✗]\e[0m $PFY_SYS_DIR still exists."
        fail=$((fail + 1))
    else
        pass=$((pass + 1))
    fi

    local bin_path="/usr/local/bin/promptify"
    [[ "$OS_TYPE" == "termux" ]] && bin_path="$PREFIX/bin/promptify"
    if [[ -e "$bin_path" ]]; then
        echo -e " \e[1;31m[✗]\e[0m Global command $bin_path still exists."
        fail=$((fail + 1))
    else
        pass=$((pass + 1))
    fi

    local junk
    for junk in "$HOME/.draw" "$HOME/.username" "$HOME/.promptify_font.flf"; do
        if [[ -e "$junk" ]]; then
            echo -e " \e[1;31m[✗]\e[0m Leftover: $junk"
            fail=$((fail + 1))
        else
            pass=$((pass + 1))
        fi
    done

    if [[ "$fail" -eq 0 ]]; then
        echo -e "\n\e[1;32m[✔] VERIFY PASS\e[0m — your system is clean."
    else
        echo -e "\n\e[1;31m[✗] VERIFY FAIL\e[0m — $fail item(s) still need attention."
    fi
    return $fail
}

# ---------------------------------------------------------------------------
# Self-contained uninstaller (lives in backup/ so it can't be lost by updates)
# ---------------------------------------------------------------------------

generate_self_uninstaller() {
    init_manifest
    [[ -f "$PFY_MANIFEST" ]] || return 1
    cat > "$PFY_UNINSTALLER" << 'SUEOF'
#!/bin/bash
# Promptify — self-contained uninstaller (generated at install time).
# Restores your system even if the Promptify program files are gone.
# Usage: bash ~/.promptify/backup/uninstall.sh [--keep-data]

MANIFEST="$HOME/.promptify/backup/system/MANIFEST"
FILES="$HOME/.promptify/backup/system/files"
PFY_SYS="$HOME/.promptify"
MANAGED_ZSHRC='source ~/.promptify/runtime/zshrc 2>/dev/null'
MANAGED_BASHRC='source ~/.promptify/runtime/bashrc 2>/dev/null'

echo "[*] Restoring your shell config from the install snapshot..."

[[ -f "$MANIFEST" ]] || { echo "[!] No snapshot found — cannot restore."; exit 1; }

restore_one() {
    local kind="$1" path="$2" rel="$3" ours="$4"
    local backup="$FILES/$rel"
    case "$kind" in
        P)
            if [[ ! -f "$backup" ]]; then return; fi
            if [[ "$path" == "$HOME/.bashrc" ]]; then
                managed="$MANAGED_BASHRC"
            else
                managed="$MANAGED_ZSHRC"
            fi
            if [[ ! -f "$path" ]] || cmp -s "$path" "$backup"; then
                [[ -f "$path" ]] || cp -p "$backup" "$path"
                return
            fi
            if grep -qF "$managed" "$path" 2>/dev/null; then
                local additions
                additions=$(grep -vF "$managed" "$path" | grep -v '^[[:space:]]*$')
                if [[ -z "$additions" ]]; then
                    cp -p "$backup" "$path"
                else
                    local tmp; tmp=$(mktemp)
                    cp -p "$backup" "$tmp"
                    echo "" >> "$tmp"
                    grep -vF "$managed" "$path" | grep -v '^[[:space:]]*$' >> "$tmp"
                    cp -p "$tmp" "$path"; rm -f "$tmp"
                fi
            else
                echo "   [i] $path was replaced by you — left as-is."
            fi
            ;;
        C)
            if [[ -f "$path" ]] && [[ "$(sha256sum "$path" 2>/dev/null | awk '{print $1}')" == "$ours" ]]; then
                rm -f "$path"
            fi
            ;;
    esac
}

while IFS='|' read -r kind path rel ours; do
    [[ "$kind" == "#"* || -z "$kind" ]] && continue
    restore_one "$kind" "$path" "$rel" "$ours"
done < "$MANIFEST"

# Remove the global command (no sudo needed if user-owned; best effort otherwise)
if [[ -w /usr/local/bin ]]; then
    rm -f /usr/local/bin/promptify 2>/dev/null
elif [[ -w "$PREFIX/bin" ]]; then
    rm -f "$PREFIX/bin/promptify" 2>/dev/null
fi

if [[ "$1" != "--keep-data" ]]; then
    rm -rf "$PFY_SYS"
    echo "[✔] Promptify removed. Your shell config is restored."
else
    echo "[✔] Shell config restored. Data kept at ~/.promptify."
fi
SUEOF
    chmod +x "$PFY_UNINSTALLER" 2>/dev/null
}
